# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.14.1
    hooks:
      - id: commitizen
  - repo: local
    hooks:
      - id: format
        name: Format code
        entry: make format
        language: system
        pass_filenames: false
      - id: lint
        name: Lint code
        entry: make lint
        language: system
        pass_filenames: false
      - id: db
        name: Update db
        entry: .venv/bin/python bin/update-db.py
        language: system
        pass_filenames: false
