---
version: "3.0"
services:
  api:
    image: morriz/indy-news:main
    # container_name: api
    ports:
      - 8080:8080
    restart: unless-stopped
    env_file:
      - .env
  swag:
    image: lscr.io/linuxserver/swag
    # command: cat /config/nginx/proxy-confs/indy-news.conf
    # container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - URL=indy-news.srv.instrukt.ai
      - VALIDATION=http
    volumes:
      - $PWD/nginx/api.conf:/config/nginx/proxy-confs/api.subdomain.conf
    ports:
      - 444:443
      - 81:80
    restart: unless-stopped