openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /media:
    get:
      summary: Search Media
      description:
        Search the curated independent media sources database for a partial
        name.
      operationId: search_media_media_get
      security:
        - APIKeyQuery: []
        - APIKeyHeader: []
        - HTTPBearer: []
      parameters:
        - name: names
          in: query
          required: true
          schema:
            type: string
            title: Names
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Source'
                title: Response Search Media Media Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /sources:
    get:
      summary: Get All Sources
      description: 'Returns a list of all sources.


        Used as input for AI to determine which sources to select for certain topics.'
      operationId: get_all_sources_sources_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SourceMinimal'
                type: array
                title: Response Get All Sources Sources Get
      security:
        - APIKeyQuery: []
        - APIKeyHeader: []
        - HTTPBearer: []
  /source-media:
    get:
      summary: Get Source Media
      description:
        Returns a list of sources' Youtube channel and X handles. Used
        as input for AI to query for videos and tweets.
      operationId: get_source_media_source_media_get
      security:
        - APIKeyQuery: []
        - APIKeyHeader: []
        - HTTPBearer: []
      parameters:
        - name: sources
          in: query
          required: false
          schema:
            anyOf:
              - type: string
                minLength: 1
              - type: 'null'
            title: Comma separated list of source names
            examples:
              - Al Jazeera,Democracy Now
          description: Source names to get Youtube channel and X handles for
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SourceMedia'
                title: Response Get Source Media Source Media Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /source-names:
    get:
      summary: Get Source Names
      description: Returns a list of source names.
      operationId: get_source_names_source_names_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
                title: Response Get Source Names Source Names Get
      security:
        - APIKeyQuery: []
        - APIKeyHeader: []
        - HTTPBearer: []
  /youtube-channels:
    get:
      summary: Get Youtube Channels
      description: Returns a list of sources' Youtube channels.
      operationId: get_youtube_channels_youtube_channels_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
                title: Response Get Youtube Channels Youtube Channels Get
      security:
        - APIKeyQuery: []
        - APIKeyHeader: []
        - HTTPBearer: []
  /x-users:
    get:
      summary: Get X Users
      description: Returns a list of sources' X user handles.
      operationId: get_x_users_x_users_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
                title: Response Get X Users X Users Get
      security:
        - APIKeyQuery: []
        - APIKeyHeader: []
        - HTTPBearer: []
  /substack-publications:
    get:
      summary: Get Substack Publications
      description: Returns a list of sources' Substack publication names.
      operationId: get_substack_publications_substack_publications_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
                title: Response Get Substack Publications Substack Publications Get
      security:
        - APIKeyQuery: []
        - APIKeyHeader: []
        - HTTPBearer: []
  /youtube:
    get:
      summary: Get Youtube Search
      description: Find Youtube videos by either providing channels, a query, or both.
      operationId: get_youtube_search_youtube_get
      security:
        - APIKeyQuery: []
        - APIKeyHeader: []
        - HTTPBearer: []
      parameters:
        - name: query
          in: query
          required: false
          schema:
            anyOf:
              - type: string
                minLength: 3
              - type: 'null'
            title: Query string
            examples:
              - israel
          description: Search query to match independent news channels
        - name: channels
          in: query
          required: false
          schema:
            anyOf:
              - type: string
              - type: 'null'
            title: Channels to search in
            examples:
              - '@aljazeeraenglish,@DemocracyNow'
          description: A string of comma-separated Youtube channels to search in.
        - name: period_days
          in: query
          required: false
          schema:
            type: integer
            title: Period in days
            default: 3
          description:
            The period in days before (now|end_date) that we want to search
            videos for.
        - name: end_date
          in: query
          required: false
          schema:
            anyOf:
              - type: string
              - type: 'null'
            title: End date
          description: End date in Y-m-d format (subtracts period_days from this)
        - name: max_videos_per_channel
          in: query
          required: false
          schema:
            type: integer
            title: Max videos per channel
            default: 2
          description:
            The maximum number of videos per channel that we want from each
            channel search.
        - name: get_descriptions
          in: query
          required: false
          schema:
            type: boolean
            title: Get descriptions
            default: false
          description: Get the long descriptions for the videos.
        - name: get_transcripts
          in: query
          required: false
          schema:
            type: boolean
            title: Get transcripts
            default: true
          description: Get the transcripts for the videos.
        - name: char_cap
          in: query
          required: false
          schema:
            anyOf:
              - type: integer
              - type: 'null'
            title: Max chars in the response
          description: The maximum number of characters for the response.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Video'
                title: Response Get Youtube Search Youtube Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /youtube-transcripts:
    get:
      summary: Get Youtube Transcripts
      description: Extract transcripts from a list of Youtube video ids.
      operationId: get_youtube_transcripts_youtube_transcripts_get
      security:
        - APIKeyQuery: []
        - APIKeyHeader: []
        - HTTPBearer: []
      parameters:
        - name: ids
          in: query
          required: true
          schema:
            type: string
            title: Ids
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VideoTranscript'
                title: Response Get Youtube Transcripts Youtube Transcripts Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    User:
      properties:
        id:
          type: integer
          title: Id
        screen_name:
          type: string
          title: Screen Name
      type: object
      required:
        - id
        - screen_name
      title: User
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
    Video:
      properties:
        id:
          type: string
          title: Id
        title:
          type: string
          title: Title
        short_desc:
          type: string
          title: Short Desc
        channel:
          type: string
          title: Channel
        duration:
          type: string
          title: Duration
        views:
          type: string
          title: Views
        publish_time:
          type: string
          title: Publish Time
        url_suffix:
          type: string
          title: Url Suffix
        long_desc:
          anyOf:
            - type: string
            - type: 'null'
          title: Long Desc
        transcript:
          anyOf:
            - type: string
            - type: 'null'
          title: Transcript
      type: object
      required:
        - id
        - title
        - short_desc
        - channel
        - duration
        - views
        - publish_time
        - url_suffix
      title: Video
      description: Video model.
    VideoTranscript:
      properties:
        id:
          type: string
          title: Id
        text:
          type: string
          title: Text
      type: object
      required:
        - id
        - text
      title: VideoTranscript
      description: Video transcript model.
  securitySchemes:
    APIKeyQuery:
      type: apiKey
      in: query
      name: apikey
    APIKeyHeader:
      type: apiKey
      in: header
      name: X-API-KEY
    HTTPBearer:
      type: http
      scheme: bearer
