alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
domains:
  - domain: indy-news.idiotz.nl
    type: PRIMARY
envs: []
ingress:
  rules:
    - component:
        name: morriz-indy-news-app
      match:
        path:
          prefix: /
name: indy-news-app
region: ams
services:
  - http_port: 8080
    image:
      registry: morriz
      registry_type: DOCKER_HUB
      repository: indy-news
      tag: main
    instance_count: 1
    instance_size_slug: basic-xxs
    name: morriz-indy-news-app
